### ISSUE TITLE
Is this the Dockerfile on Dockerhub?

### ISSUE THREAD

**Issue by Eriner** [Requarks/wiki-docker#1]
Is this repo used to build the dockerfile on Dockerhub? Instead, is it possible to put this dockerfile into the main repository and use an automated build such that the Dockerfile is included in the Hub repo?

Additionally, it would be ideal if all external dependencies (in this case, mongo) were decoupled from the application and Dockerfile. The management/running of external dependencies could be managed instead by docker-compose.

I have created a significantly slimmer image and Dockerfile for this project based on Alpine, as well as a docker-compose for this application and would be happy to contribute that back upstream if it's in the best interest of the project.

Cheers.

**Comment by NGPixel** [comment]
No, please use the image / dockerfile provided on the main project repo:
https://github.com/Requarks/wiki

The official image is already built on Alpine and does not include Mongo.

**Comment by Eriner** [comment]
Ah, this: https://github.com/Requarks/wiki/blob/master/tools/build/Dockerfile is what I was looking for. 
Cheers
